const mongoose = require('mongoose');

const empSchema = mongoose.Schema({
  //id: { type: String, required: true },
  empno: { type: Number, required: true },
  empname: { type: String, required: true },
  basictype: { type: String, required: true },
  emptype: { type: String, required: true },
  department: { type: String, required: true },
  designation: { type: String, required: true },
  group: { type: String, required: true },
  gender: { type: String, required: true },
  dob: { type: Date, required: true },
  doj: { type: Date, required: true },
  doni: { type: Date, required: true },
  doli: { type: Date, required: true },
  dor: { type: Date, required: true },
  pan: { type: String, required: true },
  gpf: { type: String, required: true },
  nps: { type: String, required: true },
  aadharno: { type: Number, required: true },

  bankname: { type: String, required: true },
  bankaccountno: { type: Number, required: true },
  ifsccode: { type: String, required: true },

  paylevel: { type: String, required: true },
  cellno: { type: Number, required: true },
  basicpay: { type: Number, required: true },
  govtqurters: { type: String, required: true },
  medicalstatus: { type: String, required: true },
  exservice: { type: String, required: true },
  ptax: { type: Number, required: true },
  cgegis: { type: Number, required: true },
  da: { type: Number, required: true },
  daamt: { type: Number, required: true },
  hra: { type: Number, required: true },
  hraamt: { type: Number, required: true },
  ta: { type: Number, required: true },
  daonta: { type: Number, required: true },
  noncghs:{ type: String, required: true },
  npssubscription: { type: Number, required: true },
  npsgovtsub: { type: Number, required: true },
  remarks: { type: String, required: true },

  status: { type: String, required: true },
  effectivedate: { type: Date, required: true },

  HBAloan: { type: String, required: true },
  HBAtype:{ type: String, required: true },
  HBAinstno:{ type: Number, required: true },
  HBAloanamt:{ type: Number, required: true },
  HBAinstamt:{ type: Number, required: true },
  //HBArec:{ type: Number, required: true },
  HBAbal:{ type: Number, required: true },
  HBAlastinst:{ type: Number, required: true },
  HBAlastdate:{ type: Date, required: true },
  HBAremarks:{ type: String, required: true },
  HBAstartdate:{ type: Date, required: true },
  HBAstatus:{ type: String, required: true },

  MCloan: { type: String, required: true },
  MCtype:{ type: String, required: true },
  MCloanamt:{ type: Number, required: true },
  MCinstno:{ type: Number, required: true },
  MCinstamt:{ type: Number, required: true },
  //MCrec:{ type: Number, required: true },
  MCbal:{ type: Number, required: true },
  MClastinst:{ type: Number, required: true },
  MClastdate:{ type: Date, required: true },
  MCremarks:{ type: String, required: true },
  MCstartdate:{ type: Date, required: true },
  MCstatus:{ type: String, required: true },

  PCloan: { type: String, required: true },
  PCtype:{ type: String, required: true },
  PCloanamt:{ type: Number, required: true },
  PCinstno:{ type: Number, required: true },
  PCinstamt:{ type: Number, required: true },
  //PCrec:{ type: Number, required: true },
  PCbal:{ type: Number, required: true },
  PClastinst:{ type: Number, required: true },
  PClastdate:{ type: Date, required: true },
  PCremarks:{ type: String, required: true },
  PCstartdate:{ type: Date, required: true },
  PCstatus:{ type: String, required: true },

  CARloan: { type: String, required: true },
  CARtype:{ type: String, required: true },
  CARloanamt:{ type: Number, required: true },
  CARinstno:{ type: Number, required: true },
  CARinstamt:{ type: Number, required: true },
  //CARrec:{ type: Number, required: true },
  CARbal:{ type: Number, required: true },
  CARlastinst:{ type: Number, required: true },
  CARlastdate:{ type: Date, required: true },
  CARremarks:{ type: String, required: true },
  CARstartdate:{ type: Date, required: true },
  CARstatus:{ type: String, required: true },

  GPFloan: { type: String, required: true },
  GPFtype:{ type: String, required: true },
  GPFloanamt:{ type: Number, required: true },
  GPFinstno:{ type: Number, required: true },
  GPFinstamt:{ type: Number, required: true },
  //GPFrec:{ type: Number, required: true },
  GPFbal:{ type: Number, required: true },
  GPFlastinst:{ type: Number, required: true },
  GPFlastdate:{ type: Date, required: true },
  GPFremarks:{ type: String, required: true },
  GPFstartdate:{ type: Date, required: true },
  GPFstatus:{ type: String, required: true },

  OTHERloan: { type: String, required: true },
  OTHERtype:{ type: String, required: true },
  OTHERloanamt:{ type: Number, required: true },
  OTHERinstno:{ type: Number, required: true },
  OTHERinstamt:{ type: Number, required: true },
  //OTHERrec:{ type: Number, required: true },
  OTHERbal:{ type: Number, required: true },
  OTHERlastinst:{ type: Number, required: true },
  OTHERlastdate:{ type: Date, required: true },
  OTHERremarks:{ type: String, required: true },
  OTHERstartdate:{ type: Date, required: true },
  OTHERstatus:{ type: String, required: true },

  gpfsub:{ type: Number, required: true },
  gpfrec:{ type: Number, required: true },
  npssub:{ type: Number, required: true },
  npsrec:{ type: Number, required: true },
  it:{ type: Number, required: true },
  ittaxamt:{ type: Number, required: true },
  cess:{ type: Number, required: true },
  misc1:{ type: Number, required: true },
  homerent:{ type: Number, required: true },
  water:{ type: Number, required: true },
  elec:{ type: Number, required: true },
  cghs:{ type: Number, required: true },
  //TaDa:{ type: Number, required: true },
  misc1Alw:{ type: Number, required: true },
 
  dlomi:{ type: Number, required: true },
  welfare:{ type: Number, required: true },
  DRDLEcss:{ type: Number, required: true },
  cqa:{ type: Number, required: true },
  OfrMisc1:{ type: Number, required: true },
  OffRecvdate:{ type: Date, required: true },

  grosspay:{ type: Number, required: true },
  tdeduction:{ type: Number, required: true },
  netpay:{ type: Number, required: true },
  toffcrec:{ type: Number, required: true },
  tobnkamt:{ type: Number, required: true },

  creator: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true }
});

module.exports = mongoose.model('Employee', empSchema);
